export let content = {
    English: {
        // update:"Need a Easy, Simple, Cheap & Trusted Agent?"
        update:"Need a Easy, Simple, Cheap & Trusted Agent?",
        ck:"Click Here",
        title:"Latest News",
        sub:"Click anywhere to close",
        desc:"Starting March 7, 2022, Indonesia will reopen for all international tourists from 23 countries with Visa On Arrival ( VOA ) to visit BALI\n(The Visa on Arrival Scheme is only valid for citizens of 23 registered countries).\n\nFurther information : \n✅ Foreign travelers still have to meet certain requirements to enter Bali during this trial period,\n✅ Visa on Arrival will return for 23 selected countries, but at this stage it is not a FREE entry that you may use to enter. It appears the visa will be IDR 500,000 ($50 AUD) per person and will allow you to stay up to 30 days (you can also choose to pay for an extension which will give you a 60 day stay). If you are from a country not on the list, you can still visit but you must apply for a B211A visa prior to arrival.\nSuch as proof of payment for a minimum 4 days accommodation booking (proof of residency for KITAS holders), Four nights at one of the approved hotels by the government and must ordered before arriving. After the PCR test at the airport, you go straight to the hotel. Once your results come back, if you are negative, you are free to explore Bali (this only takes a few hours). If you are positive, you will need to isolate (apparently for a period of 3 days but waiting for full confirmation where).\n*Hotel from the list approved by the Government*\n✅ PCR test on arrival (tourists are required to wait for a negative result at the accommodation pre-ordered).\n✅ Fully vaccinated or booster injection, negative PCR test result again on the 3rd day as a guarantee to be virus free.\n✅ If positive, travelers with virus symptoms, and especially the elderly, will be transferred to the hospital for isolation and treatment.\n✅ On the 3rd day the traveler has to do the 2nd PCR test at one of the approved hotels by the government to make sure it is virus free. If the test result is negative, the traveler can check-out from the hotel on the 4th day.\n✅ The traveler must have health insurance that covers covid-19. (Minimum $25,000 USD)\n\n🔥 BALI IS BACK "
    },
    Indonesia:{
        // update:"Perlu Pelayanan yang Mudah, Sederhana, Murah dan Terpercaya?"
        update:"Perlu Pelayanan yang Mudah, Sederhana, Murah dan Terpercaya?",
        ck:"Klik Disini",
        title:"Berita Terkini",
        sub:"Klik dimanapun untuk tutup",
        desc:"Mulai 7 Maret 2022, Indonesia akan dibuka kembali untuk semua wisatawan internasional dari 23 negara dengan Visa On Arrival ( VOA ) untuk mengunjungi BALI\n(Skema Visa on Arrival hanya berlaku untuk warga negara dari 23 negara yang terdaftar).\n\nInformasi lebih lanjut : \n✅ Wisatawan asing masih harus memenuhi persyaratan tertentu untuk masuk ke Bali selama masa percobaan ini,\n✅ Visa on Arrival akan kembali untuk 23 negara terpilih, tetapi pada tahap ini bukan entri GRATIS yang dapat Anda gunakan untuk masuk. Tampaknya visa akan menjadi Rp 500.000 ($50 AUD) per orang dan akan memungkinkan Anda untuk tinggal hingga 30 hari (Anda juga dapat memilih untuk membayar perpanjangan yang akan memberi Anda masa tinggal 60 hari). Jika Anda berasal dari negara yang tidak ada dalam daftar, Anda tetap dapat berkunjung tetapi Anda harus mengajukan visa B211A sebelum kedatangan.\nSeperti bukti pembayaran untuk pemesanan akomodasi minimal 4 hari (bukti tempat tinggal bagi pemegang KITAS), Empat malam di salah satu hotel yang disetujui oleh pemerintah dan harus dipesan sebelum tiba. Setelah tes PCR di bandara, Anda langsung menuju hotel. Setelah hasil Anda kembali, jika Anda negatif, Anda bebas menjelajahi Bali (ini hanya membutuhkan waktu beberapa jam). Jika Anda positif, Anda perlu mengisolasi (ternyata untuk jangka waktu 3 hari tetapi menunggu konfirmasi penuh di mana).\n*Hotel dari daftar yang disetujui oleh Pemerintah*\n✅ Tes PCR pada saat kedatangan (turis diharuskan untuk tunggu hasil negatif di penginapan yang dipesan sebelumnya).\n✅ Vaksin lengkap atau booster injeksi, hasil tes PCR negatif lagi pada hari ke-3 sebagai jaminan bebas virus.\n✅ Jika positif, pelancong dengan gejala virus, dan terutama orang tua, akan dipindahkan ke rumah sakit untuk isolasi dan perawatan.\n✅ Pada hari ke-3 traveler harus melakukan tes PCR ke-2 di salah satu hotel yang disetujui oleh pemerintah untuk memastikan bebas virus. Jika hasil tes negatif, traveler bisa check-out dari hotel pada hari ke-4.\n✅ Traveler harus memiliki asuransi kesehatan yang mengcover covid-19. (Minimum $25.000 USD)\n\n🔥 BALI KEMBALI"
    }
  };