export let content = {
    English: {
      heading:"About Us",
      desc:"BCS ( CV. Bali Connection Service) was established in 2005 until now. Our company has many years of experience assisting with visa processing abroad and within the country for both Domestic Tourists and Expatriates / Foreign Residents in Indonesia. \n\nWe have more than 20 years of experience helping with all types of travel documents, including visas abroad and permits in Bali / Indonesia. Especially visa assistance abroad, as we know that the Embassy refuses many Visa applicants access because their documents are incomplete.  \n\nThat's why We, BCS, specialize in all aspects of visa requirements. We can guide you step by step into your visa application until you get a successful outcome—the Indonesian Immigration Office. \n\nOur friendly staff will assist you and provide a proper and complete consultation, especially in; \nHoliday Visa, \nBusiness Visa, \nRetirement Visa, \nSpouse Visa in Australia, \nVisa Extension, \nSocial Visa, \nEtc.\nWe, BCS, will guarantee that 99% of visas will be approved.\n\nWE SERVE YOU SINCERELY BECAUSE YOUR SATISFACTION IS OUR GOAL."
    },  
    Indonesia:{
      heading:"Tentang Kami",
      desc:"BCS ( CV. Bali Connection Service), didirikan sejak tahun 2005 sampai saat ini. Perusahaan kami tentunya telah memiliki pengalaman bertahun-tahun dalam membantu pengurusan visa keluar negeri dan dalam Negeri baik untuk Wisatawan Domestik maupun  dan Warga Ekspatriat/ Warga Asing di Indonesia. \n\nDengan memiliki pengalaman lebih dari 20 tahun itulah, kami sungguh mengetahui dokumen dokumen yang diperlukan untuk pengurusan visa keluar Negeri, dengan Jaminan 99 % semua visa aplikasi disetujui oleh pihak Kedutaan.Teristimewa pengurusan Visa aplikasi keluar negeri. Seperti yang kita ketahui bahwa banyak pemohon Visa yang ditolak visanya oleh Kedutaan dikarenakan alasan dokumen visa aplikasi tidak lengkap. \n\nOleh karena itu Kantor kami, BCS akan memberikan konsultasi dan saran yang benar untuk melengkapi semua persyaratan dokumen aplikasi sebelum diajukan ke Kedutaan / Konsulat terkait. Disamping itu, kami juga membantu untuk pengurusan visa kunjungan ke Indonesia, terutama Bali seperti: \nPerpanjangan VOA,\nVisa B211,\nVisa Social Budaya,\nKitas Pensiun/Kerja/Family,\nPMA,\nDan Lain-lain. \n\nKAMI MELAYANI ANDA DENGAN SETULUS HATI KARENA KEPUASAN ANDA ADALAH TUJUAN KAMI."
    }
  };