export { default as visa} from '../../assets/visa-abroad.webp'
export { default as dots} from '../../assets/dots.svg'
export { default as bali} from '../../assets/visa-bali.webp'
export { default as wedding} from '../../assets/married.webp'
export { default as translate} from '../../assets/translate.webp'
export { default as travel} from '../../assets/travel.webp'
export { default as info} from '../../assets/info.webp'
export { default as heroImage } from '../../assets/hero.webp'
export { default as logoIcon } from '../../assets/logo.svg'
export { default as Pattern } from '../../assets/pattern.svg'
export { default as Vinsen} from '../../assets/bali.webp'
export { default as NotifContent } from '../../assets/notifcontent.webp'
export { default as NotifPNG } from '../../assets/notifcontent.png'
export { default as NyepiContent } from '../../assets/notifnyepi.webp'
export { default as NyepiPNG } from '../../assets/notifnyepi.png'
